spring.datasource.url: jdbc:mysql://localhost:3306/tasklib?useUnicode=true&characterEncoding=utf8&serverTimeZone=UTC
spring.datasource.username: root
spring.datasource.password: Khol@1406
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: create